const baseConfig = {
          darkMode: "class",
          theme: {
            extend: {
              colors: {
                "tertiary-fixed": "#ecf5f9",
                "on-tertiary": "#576064",
                "surface-container-lowest": "#000000",
                "on-secondary": "#0d232b",
                "primary-container": "#773200",
                "on-secondary-fixed": "#2d424c",
                "surface-variant": "#20262c",
                "surface-container": "#161a1e",
                "secondary-fixed-dim": "#c1d8e4",
                "surface-dim": "#0c0e10",
                "on-error": "#490106",
                "inverse-surface": "#f9f9fc",
                "on-secondary-container": "#acc3ce",
                "secondary": "#8ba1ac",
                "on-primary-container": "#ffc3a4",
                "outline": "#70767c",
                "inverse-primary": "#9d4500",
                "error": "#ee7d77",
                "on-tertiary-fixed": "#424b4e",
                "tertiary": "#f2fbff",
                "secondary-fixed": "#cfe6f2",
                "secondary-container": "#293e48",
                "on-surface": "#e0e6ed",
                "surface-container-high": "#1b2025",
                "on-error-container": "#ff9993",
                "on-secondary-fixed-variant": "#495f69",
                "on-primary-fixed-variant": "#984200",
                "primary-fixed": "#ffdbca",
                "surface-container-low": "#111416",
                "surface": "#0c0e10",
                "error-container": "#7f2927",
                "secondary-dim": "#8ba1ac",
                "primary": "#ffb68f",
                "on-primary": "#6d2d00",
                "tertiary-dim": "#e3ecf0",
                "surface-tint": "#ffb68f",
                "primary-fixed-dim": "#ffc9ad",
                "on-tertiary-fixed-variant": "#5f686b",
                "inverse-on-surface": "#535557",
                "outline-variant": "#42494e",
                "on-surface-variant": "#a6acb2",
                "on-tertiary-container": "#4f585c",
                "surface-container-highest": "#20262c",
                "primary-dim": "#ffa26e",
                "on-primary-fixed": "#6b2d00",
                "surface-bright": "#252d33",
                "tertiary-fixed-dim": "#dee7eb",
                "background": "#0c0e10",
                "tertiary-container": "#e3ecf0",
                "on-background": "#e0e6ed",
                "error-dim": "#bb5551"
              },
              fontFamily: {
                "headline": ["Inter"],
                "body": ["Public Sans"],
                "label": ["Space Grotesk"]
              },
              borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
            },
          },
        };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-b2b-servicios-stitch-02b.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
