const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface": "#f9f9fc",
              "secondary-fixed-dim": "#c6c6c9",
              "on-secondary-fixed-variant": "#454749",
              "surface-dim": "#dadadc",
              "tertiary-fixed-dim": "#e9c349",
              "on-surface-variant": "#434656",
              "outline-variant": "#c3c5d9",
              "on-primary": "#ffffff",
              "error": "#ba1a1a",
              "primary": "#0040cb",
              "on-secondary-container": "#636467",
              "secondary-fixed": "#e2e2e5",
              "surface-container-highest": "#e2e2e5",
              "on-tertiary": "#ffffff",
              "surface-container-low": "#f3f3f6",
              "tertiary": "#735c00",
              "on-surface": "#1a1c1e",
              "surface-container-high": "#e8e8ea",
              "background": "#f9f9fc",
              "on-primary-container": "#e3e6ff",
              "on-primary-fixed": "#001452",
              "surface-container": "#eeeef0",
              "inverse-primary": "#b7c4ff",
              "secondary": "#5d5e61",
              "inverse-surface": "#2f3133",
              "inverse-on-surface": "#f0f0f3",
              "on-tertiary-fixed": "#241a00",
              "surface-variant": "#e2e2e5",
              "on-tertiary-fixed-variant": "#574500",
              "outline": "#737688",
              "on-primary-fixed-variant": "#0038b6",
              "on-secondary-fixed": "#1a1c1e",
              "on-secondary": "#ffffff",
              "surface-tint": "#004ced",
              "on-error": "#ffffff",
              "primary-container": "#0c54ff",
              "surface-bright": "#f9f9fc",
              "error-container": "#ffdad6",
              "primary-fixed-dim": "#b7c4ff",
              "surface-container-lowest": "#ffffff",
              "on-error-container": "#93000a",
              "tertiary-fixed": "#ffe088",
              "tertiary-container": "#cca730",
              "secondary-container": "#e2e2e5",
              "on-background": "#1a1c1e",
              "primary-fixed": "#dde1ff",
              "on-tertiary-container": "#4e3d00"
            },
            fontFamily: {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-hotel-alojamiento-stitch-03.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
