const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface-container-high": "#2a2a2a",
              "surface-container-low": "#1c1b1b",
              "on-primary": "#452b00",
              "on-surface-variant": "#d5c4b1",
              "on-tertiary-fixed": "#001e30",
              "surface-dim": "#131313",
              "on-tertiary-fixed-variant": "#004b71",
              "on-primary-container": "#5b3a00",
              "tertiary": "#92ceff",
              "primary-fixed": "#ffddb5",
              "secondary-container": "#7a2f10",
              "on-error": "#690005",
              "surface-container-highest": "#353534",
              "outline-variant": "#514536",
              "primary-container": "#e2a03f",
              "on-secondary": "#5b1a00",
              "on-primary-fixed-variant": "#633f00",
              "surface-bright": "#393939",
              "background": "#131313",
              "error": "#ffb4ab",
              "secondary-fixed-dim": "#ffb59b",
              "primary-fixed-dim": "#ffb956",
              "tertiary-fixed-dim": "#8ecdff",
              "on-tertiary": "#00344f",
              "secondary-fixed": "#ffdbcf",
              "surface-container-lowest": "#0e0e0e",
              "on-surface": "#e5e2e1",
              "error-container": "#93000a",
              "inverse-primary": "#835400",
              "on-secondary-fixed-variant": "#7a2f10",
              "on-background": "#e5e2e1",
              "secondary": "#ffb59b",
              "on-tertiary-container": "#004568",
              "primary": "#ffbc5d",
              "on-primary-fixed": "#2a1800",
              "surface-variant": "#353534",
              "on-secondary-fixed": "#380d00",
              "on-error-container": "#ffdad6",
              "on-secondary-container": "#ff9b77",
              "surface": "#131313",
              "inverse-on-surface": "#313030",
              "surface-container": "#201f1f",
              "surface-tint": "#ffb956",
              "inverse-surface": "#e5e2e1",
              "outline": "#9e8e7d",
              "tertiary-fixed": "#cbe6ff",
              "tertiary-container": "#66b4ed"
            },
            fontFamily: {
              "headline": ["Noto Serif"],
              "body": ["Manrope"],
              "label": ["Manrope"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-hotel-alojamiento-stitch-02.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
