const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-surface-variant": "#44464e",
              "primary-container": "#0a1f44",
              "on-secondary-fixed": "#021f29",
              "surface-container-high": "#e6e8e9",
              "secondary": "#48626e",
              "outline-variant": "#c5c6cf",
              "on-tertiary-container": "#e26000",
              "surface-container-highest": "#e1e3e4",
              "surface-container-low": "#f2f4f5",
              "outline": "#75777f",
              "on-primary-fixed": "#041a3f",
              "primary-fixed": "#d9e2ff",
              "background": "#f8fafb",
              "tertiary": "#160400",
              "on-background": "#191c1d",
              "tertiary-fixed-dim": "#ffb692",
              "on-secondary-container": "#4e6874",
              "inverse-primary": "#b4c6f4",
              "primary": "#00081e",
              "on-error": "#ffffff",
              "on-tertiary-fixed": "#341100",
              "on-secondary-fixed-variant": "#304a55",
              "on-primary-fixed-variant": "#34466d",
              "on-tertiary": "#ffffff",
              "on-primary": "#ffffff",
              "on-secondary": "#ffffff",
              "surface": "#f8fafb",
              "error": "#ba1a1a",
              "on-surface": "#191c1d",
              "on-error-container": "#93000a",
              "inverse-on-surface": "#eff1f2",
              "secondary-container": "#cbe7f5",
              "error-container": "#ffdad6",
              "primary-fixed-dim": "#b4c6f4",
              "secondary-fixed-dim": "#afcbd8",
              "tertiary-fixed": "#ffdbcb",
              "surface-variant": "#e1e3e4",
              "tertiary-container": "#3c1400",
              "surface-bright": "#f8fafb",
              "surface-dim": "#d8dadb",
              "surface-tint": "#4c5e86",
              "surface-container": "#eceeef",
              "surface-container-lowest": "#ffffff",
              "secondary-fixed": "#cbe7f5",
              "on-primary-container": "#7687b2",
              "on-tertiary-fixed-variant": "#7a3000",
              "inverse-surface": "#2e3132"
            },
            fontFamily: {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-instalador-constructor-stitch-01.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
