const baseConfig = {
          darkMode: "class",
          theme: {
            extend: {
              colors: {
                "surface-container-highest": "#353535",
                "outline-variant": "#5a4136",
                "secondary-container": "#7b3409",
                "on-error": "#690005",
                "primary-fixed": "#ffdbcc",
                "tertiary": "#9ccaff",
                "secondary-fixed-dim": "#ffb693",
                "error": "#ffb4ab",
                "background": "#131313",
                "surface-bright": "#393939",
                "on-primary-fixed-variant": "#7a3000",
                "primary-container": "#ff6b00",
                "on-secondary": "#561f00",
                "surface-container-high": "#2a2a2a",
                "on-primary-container": "#572000",
                "on-tertiary-fixed-variant": "#00497b",
                "on-tertiary-fixed": "#001d35",
                "surface-dim": "#131313",
                "on-surface-variant": "#e2bfb0",
                "on-primary": "#561f00",
                "surface-container-low": "#1c1b1b",
                "on-secondary-fixed": "#351000",
                "surface-variant": "#353535",
                "on-primary-fixed": "#351000",
                "primary": "#ffb693",
                "on-tertiary-container": "#003357",
                "secondary": "#ffb693",
                "on-background": "#e5e2e1",
                "tertiary-container": "#059eff",
                "outline": "#a98a7d",
                "tertiary-fixed": "#d0e4ff",
                "surface-tint": "#ffb693",
                "inverse-surface": "#e5e2e1",
                "surface-container": "#20201f",
                "on-secondary-container": "#ffa173",
                "surface": "#131313",
                "inverse-on-surface": "#313030",
                "on-error-container": "#ffdad6",
                "secondary-fixed": "#ffdbcc",
                "on-tertiary": "#003257",
                "tertiary-fixed-dim": "#9ccaff",
                "primary-fixed-dim": "#ffb693",
                "on-secondary-fixed-variant": "#783207",
                "inverse-primary": "#a04100",
                "surface-container-lowest": "#0e0e0e",
                "on-surface": "#e5e2e1",
                "error-container": "#93000a"
              },
              fontFamily: {
                "headline": ["Space Grotesk"],
                "body": ["Inter"],
                "label": ["Space Grotesk"]
              },
              borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
            },
          },
        };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-instalador-constructor-stitch-02.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
