const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-tertiary-container": "#e08359",
              "primary-fixed-dim": "#a7c8ff",
              "on-error": "#ffffff",
              "on-error-container": "#93000a",
              "surface-container-low": "#f6f3ee",
              "on-background": "#1c1c19",
              "secondary-fixed": "#ffddb9",
              "primary-container": "#003366",
              "outline": "#737780",
              "surface-container-highest": "#e5e2dd",
              "surface-container-lowest": "#ffffff",
              "on-primary-fixed-variant": "#1f477b",
              "surface-tint": "#3a5f94",
              "error": "#ba1a1a",
              "secondary": "#785833",
              "on-tertiary-fixed-variant": "#77320e",
              "on-surface": "#1c1c19",
              "primary-fixed": "#d5e3ff",
              "on-secondary": "#ffffff",
              "on-secondary-fixed": "#2b1700",
              "secondary-fixed-dim": "#e9bf91",
              "secondary-container": "#fed2a3",
              "on-primary-fixed": "#001b3c",
              "inverse-primary": "#a7c8ff",
              "tertiary-fixed": "#ffdbcd",
              "surface-variant": "#e5e2dd",
              "tertiary": "#3a1100",
              "surface-bright": "#fcf9f4",
              "primary": "#001e40",
              "outline-variant": "#c3c6d1",
              "inverse-on-surface": "#f3f0eb",
              "surface-container": "#f0ede8",
              "surface-dim": "#dcdad5",
              "on-primary-container": "#799dd6",
              "on-tertiary": "#ffffff",
              "on-tertiary-fixed": "#360f00",
              "background": "#fcf9f4",
              "surface": "#fcf9f4",
              "on-surface-variant": "#43474f",
              "on-secondary-fixed-variant": "#5e411e",
              "tertiary-fixed-dim": "#ffb597",
              "on-primary": "#ffffff",
              "on-secondary-container": "#795933",
              "surface-container-high": "#ebe8e3",
              "inverse-surface": "#31302d",
              "tertiary-container": "#5d1f00",
              "error-container": "#ffdad6"
            },
            fontFamily: {
              "headline": ["Noto Serif"],
              "body": ["Manrope"],
              "label": ["Manrope"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-hotel-alojamiento-stitch-01.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
