const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "tertiary-fixed-dim": "#d2edce",
              "surface-container-highest": "#e0e4dc",
              "on-error-container": "#752121",
              "error": "#9f403d",
              "on-secondary-fixed": "#3e4040",
              "surface-container": "#edeee8",
              "on-primary-container": "#525151",
              "secondary": "#5e5f5f",
              "on-primary-fixed": "#403f3f",
              "surface-variant": "#e0e4dc",
              "surface-container-high": "#e6e9e2",
              "surface-bright": "#faf9f5",
              "on-secondary-container": "#505252",
              "on-tertiary-fixed-variant": "#546c54",
              "surface-dim": "#d6dcd2",
              "outline": "#787c75",
              "background": "#faf9f5",
              "error-dim": "#4e0309",
              "primary-fixed": "#e5e2e1",
              "tertiary-fixed": "#e0fbdc",
              "primary": "#5f5e5e",
              "inverse-on-surface": "#9d9d9a",
              "tertiary-container": "#e0fbdc",
              "surface-tint": "#5f5e5e",
              "on-tertiary-container": "#4a614a",
              "on-error": "#fff7f6",
              "outline-variant": "#afb3ac",
              "on-background": "#2f342e",
              "on-secondary-fixed-variant": "#5a5c5c",
              "on-secondary": "#f9f9f9",
              "secondary-fixed": "#e2e2e2",
              "surface-container-low": "#f4f4ef",
              "secondary-dim": "#525353",
              "surface-container-lowest": "#ffffff",
              "inverse-primary": "#ffffff",
              "inverse-surface": "#0d0f0d",
              "tertiary": "#4e654d",
              "surface": "#faf9f5",
              "on-primary-fixed-variant": "#5c5b5b",
              "secondary-fixed-dim": "#d4d4d4",
              "primary-fixed-dim": "#d6d4d3",
              "tertiary-dim": "#425942",
              "on-surface-variant": "#5c605a",
              "on-primary": "#faf7f6",
              "on-tertiary-fixed": "#394f39",
              "on-surface": "#2f342e",
              "secondary-container": "#e2e2e2",
              "error-container": "#fe8983",
              "on-tertiary": "#e9ffe5",
              "primary-container": "#e5e2e1",
              "primary-dim": "#535252"
            },
            fontFamily: {
              "headline": ["Noto Serif"],
              "body": ["Manrope"],
              "label": ["Manrope"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-restauracion-stitch-02.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
