const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-secondary-fixed-variant": "#5d4201",
              "tertiary": "#00595a",
              "surface-tint": "#9a442a",
              "surface-container-highest": "#e4e2dd",
              "on-tertiary-fixed": "#002020",
              "on-secondary-fixed": "#261900",
              "outline-variant": "#dcc1ba",
              "surface-container-low": "#f5f3ee",
              "secondary-container": "#fed488",
              "surface-bright": "#fbf9f4",
              "error-container": "#ffdad6",
              "on-primary-fixed": "#3a0a00",
              "on-surface-variant": "#55423d",
              "tertiary-container": "#007375",
              "primary-fixed-dim": "#ffb59f",
              "outline": "#88726c",
              "on-error": "#ffffff",
              "inverse-surface": "#30312e",
              "on-tertiary-fixed-variant": "#004f51",
              "on-secondary-container": "#785a1a",
              "primary-container": "#a64d32",
              "tertiary-fixed-dim": "#7fd5d6",
              "surface-container-high": "#eae8e3",
              "on-secondary": "#ffffff",
              "on-tertiary": "#ffffff",
              "surface": "#fbf9f4",
              "secondary-fixed-dim": "#e9c176",
              "tertiary-fixed": "#9bf1f3",
              "primary": "#87361d",
              "on-surface": "#1b1c19",
              "on-primary-fixed-variant": "#7c2e15",
              "surface-variant": "#e4e2dd",
              "surface-container-lowest": "#ffffff",
              "primary-fixed": "#ffdbd1",
              "on-tertiary-container": "#9ff5f7",
              "inverse-primary": "#ffb59f",
              "on-error-container": "#93000a",
              "surface-dim": "#dbdad5",
              "secondary": "#775a19",
              "error": "#ba1a1a",
              "surface-container": "#f0eee9",
              "inverse-on-surface": "#f2f1ec",
              "secondary-fixed": "#ffdea5",
              "background": "#fbf9f4",
              "on-background": "#1b1c19",
              "on-primary": "#ffffff",
              "on-primary-container": "#ffe0d8"
            },
            fontFamily: {
              "headline": ["Newsreader", "serif"],
              "body": ["Manrope", "sans-serif"],
              "label": ["Manrope", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-b2b-servicios-stitch-03.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
