const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-secondary-fixed-variant": "#3c475a",
              "inverse-primary": "#b7c4ff",
              "on-surface": "#131b2e",
              "error-container": "#ffdad6",
              "surface-container-lowest": "#ffffff",
              "secondary-fixed": "#d8e3fb",
              "tertiary-fixed-dim": "#ffb59a",
              "on-tertiary": "#ffffff",
              "primary-fixed-dim": "#b7c4ff",
              "tertiary-container": "#b43f00",
              "surface-tint": "#004ced",
              "inverse-surface": "#283044",
              "tertiary-fixed": "#ffdbce",
              "outline": "#737688",
              "inverse-on-surface": "#eef0ff",
              "surface": "#faf8ff",
              "on-secondary-container": "#586377",
              "surface-container": "#eaedff",
              "on-error-container": "#93000a",
              "on-secondary-fixed": "#111c2d",
              "primary": "#003ec7",
              "surface-variant": "#dae2fd",
              "on-primary-fixed": "#001452",
              "on-tertiary-container": "#ffded2",
              "on-background": "#131b2e",
              "secondary": "#545f73",
              "on-tertiary-fixed-variant": "#802a00",
              "on-primary-container": "#dfe3ff",
              "on-surface-variant": "#434656",
              "surface-dim": "#d2d9f4",
              "on-tertiary-fixed": "#370e00",
              "surface-container-low": "#f2f3ff",
              "on-primary": "#ffffff",
              "surface-container-high": "#e2e7ff",
              "secondary-fixed-dim": "#bcc7de",
              "surface-bright": "#faf8ff",
              "error": "#ba1a1a",
              "background": "#faf8ff",
              "on-secondary": "#ffffff",
              "primary-container": "#0052ff",
              "on-primary-fixed-variant": "#0038b6",
              "outline-variant": "#c3c5d9",
              "surface-container-highest": "#dae2fd",
              "secondary-container": "#d5e0f8",
              "on-error": "#ffffff",
              "tertiary": "#8c2f00",
              "primary-fixed": "#dde1ff"
            },
            fontFamily: {
              "headline": ["Plus Jakarta Sans"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-academia-formacion-stitch-02.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
