const baseConfig = {
          darkMode: "class",
          theme: {
            extend: {
              colors: {
                "tertiary-container": "#dae2fd",
                "surface-container": "#e8eff3",
                "outline-variant": "#a9b4b9",
                "tertiary": "#575f75",
                "on-tertiary": "#f9f8ff",
                "surface-tint": "#455f88",
                "on-error-container": "#752121",
                "surface-variant": "#d9e4ea",
                "on-surface-variant": "#566166",
                "on-primary-container": "#38527b",
                "on-error": "#fff7f6",
                "background": "#f7f9fb",
                "on-surface": "#2a3439",
                "surface-dim": "#cfdce3",
                "secondary-fixed": "#d3e4fe",
                "surface-container-low": "#f0f4f7",
                "on-primary": "#f6f7ff",
                "error-dim": "#4e0309",
                "secondary": "#506076",
                "primary-fixed-dim": "#bfd5ff",
                "surface": "#f7f9fb",
                "secondary-container": "#d3e4fe",
                "inverse-surface": "#0b0f10",
                "primary-container": "#d6e3ff",
                "primary": "#455f88",
                "inverse-primary": "#b3cdfd",
                "tertiary-fixed-dim": "#ccd4ee",
                "secondary-dim": "#44546a",
                "on-secondary-container": "#435368",
                "tertiary-fixed": "#dae2fd",
                "on-secondary-fixed-variant": "#4d5d73",
                "on-primary-fixed": "#254067",
                "primary-dim": "#39537c",
                "on-tertiary-container": "#4a5167",
                "outline": "#717c82",
                "error": "#9f403d",
                "surface-container-high": "#e1e9ee",
                "surface-bright": "#f7f9fb",
                "on-primary-fixed-variant": "#425c85",
                "secondary-fixed-dim": "#c5d6f0",
                "on-secondary-fixed": "#314055",
                "inverse-on-surface": "#9a9d9f",
                "on-tertiary-fixed-variant": "#535b71",
                "on-tertiary-fixed": "#373f54",
                "on-secondary": "#f7f9ff",
                "primary-fixed": "#d6e3ff",
                "on-background": "#2a3439",
                "tertiary-dim": "#4b5369",
                "surface-container-highest": "#d9e4ea",
                "error-container": "#fe8983",
                "surface-container-lowest": "#ffffff"
              },
              fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
              },
              borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
            },
          },
        };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-b2b-servicios-stitch-01b.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
