const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "tertiary-fixed": "#ffdbcb",
              "primary-container": "#00235a",
              "background": "#f4faff",
              "inverse-surface": "#263238",
              "tertiary": "#240900",
              "on-background": "#111d23",
              "outline": "#75777d",
              "primary": "#000f30",
              "surface-tint": "#2b5bb5",
              "on-tertiary": "#ffffff",
              "on-secondary-fixed-variant": "#394951",
              "secondary-fixed-dim": "#b8c9d3",
              "inverse-on-surface": "#e6f3fb",
              "on-tertiary-fixed-variant": "#7a3000",
              "on-secondary-fixed": "#0d1e25",
              "tertiary-fixed-dim": "#ffb692",
              "on-error": "#ffffff",
              "surface-dim": "#cfdce4",
              "on-primary": "#ffffff",
              "surface-variant": "#d7e4ec",
              "surface-container-highest": "#d7e4ec",
              "error": "#ba1a1a",
              "primary-fixed-dim": "#b0c6ff",
              "surface-container-lowest": "#ffffff",
              "error-container": "#ffdad6",
              "on-secondary-container": "#55656d",
              "primary-fixed": "#d9e2ff",
              "on-surface-variant": "#45474d",
              "tertiary-container": "#451800",
              "surface-container-low": "#e9f6fd",
              "on-error-container": "#93000a",
              "surface-container-high": "#ddeaf2",
              "on-primary-fixed-variant": "#00429c",
              "surface-container": "#e3f0f8",
              "on-primary-fixed": "#001945",
              "on-primary-container": "#608ae8",
              "surface": "#f4faff",
              "on-tertiary-fixed": "#341100",
              "secondary-container": "#d1e2ec",
              "inverse-primary": "#b0c6ff",
              "surface-bright": "#f4faff",
              "on-secondary": "#ffffff",
              "secondary": "#506169",
              "on-surface": "#111d23",
              "on-tertiary-container": "#ea6400",
              "secondary-fixed": "#d4e5ef",
              "outline-variant": "#c5c6cd"
            },
            fontFamily: {
              "headline": ["Space Grotesk"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-instalador-constructor-stitch-03.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
