const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "error": "#ee7d77",
              "surface-container-lowest": "#000000",
              "error-container": "#7f2927",
              "on-secondary-container": "#acc3ce",
              "primary-fixed": "#ffdbca",
              "tertiary-container": "#e3ecf0",
              "on-error-container": "#ff9993",
              "surface-container": "#161a1e",
              "surface": "#0c0e10",
              "on-tertiary-fixed": "#424b4e",
              "inverse-primary": "#9d4500",
              "secondary": "#8ba1ac",
              "on-secondary": "#0d232b",
              "on-tertiary-container": "#4f585c",
              "secondary-fixed": "#cfe6f2",
              "tertiary-dim": "#e3ecf0",
              "primary-dim": "#ffa26e",
              "background": "#0c0e10",
              "inverse-surface": "#f9f9fc",
              "tertiary": "#f2fbff",
              "on-background": "#e0e6ed",
              "primary": "#ffb68f",
              "on-tertiary": "#576064",
              "on-secondary-fixed-variant": "#495f69",
              "secondary-fixed-dim": "#c1d8e4",
              "inverse-on-surface": "#535557",
              "on-primary": "#6d2d00",
              "secondary-dim": "#8ba1ac",
              "surface-variant": "#20262c",
              "surface-container-highest": "#20262c",
              "primary-fixed-dim": "#ffc9ad",
              "on-surface-variant": "#a6acb2",
              "surface-container-low": "#111416",
              "surface-container-high": "#1b2025",
              "on-primary-fixed-variant": "#984200",
              "on-primary-fixed": "#6b2d00",
              "on-primary-container": "#ffc3a4",
              "error-dim": "#bb5551",
              "secondary-container": "#293e48",
              "surface-bright": "#252d33",
              "on-surface": "#e0e6ed",
              "outline-variant": "#42494e",
              "tertiary-fixed": "#ecf5f9",
              "primary-container": "#773200",
              "outline": "#70767c",
              "surface-tint": "#ffb68f",
              "on-secondary-fixed": "#2d424c",
              "on-tertiary-fixed-variant": "#5f686b",
              "tertiary-fixed-dim": "#dee7eb",
              "on-error": "#490106",
              "surface-dim": "#0c0e10"
            },
            fontFamily: {
              "headline": ["Inter"],
              "body": ["Public Sans"],
              "label": ["Space Grotesk"]
            },
            borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-b2b-servicios-stitch-02.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
