const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-secondary": "#5e1700",
              "inverse-surface": "#e5e2e1",
              "on-primary-fixed": "#3a0b00",
              "tertiary-fixed": "#d4e3ff",
              "surface-container-highest": "#353534",
              "tertiary": "#a5c8ff",
              "on-surface-variant": "#e6beb2",
              "secondary": "#ffb59e",
              "error-container": "#93000a",
              "primary-fixed-dim": "#ffb59e",
              "on-tertiary-fixed": "#001c3a",
              "on-background": "#e5e2e1",
              "inverse-primary": "#ae3200",
              "on-tertiary": "#00315e",
              "on-surface": "#e5e2e1",
              "tertiary-container": "#2492ff",
              "outline": "#ad897e",
              "surface-bright": "#3a3939",
              "secondary-fixed": "#ffdbd0",
              "surface-variant": "#353534",
              "secondary-container": "#842502",
              "on-primary": "#5e1700",
              "background": "#131313",
              "on-error": "#690005",
              "primary-fixed": "#ffdbd0",
              "primary-container": "#ff571a",
              "surface-tint": "#ffb59e",
              "tertiary-fixed-dim": "#a5c8ff",
              "inverse-on-surface": "#313030",
              "on-primary-container": "#521300",
              "surface-container-low": "#1c1b1b",
              "secondary-fixed-dim": "#ffb59e",
              "on-secondary-fixed": "#3a0b00",
              "surface-dim": "#131313",
              "error": "#ffb4ab",
              "on-error-container": "#ffdad6",
              "on-secondary-container": "#ff9b7c",
              "surface": "#131313",
              "on-secondary-fixed-variant": "#842502",
              "primary": "#ffb59e",
              "on-tertiary-container": "#002a53",
              "outline-variant": "#5c4037",
              "surface-container-high": "#2a2a2a",
              "surface-container": "#201f1f",
              "surface-container-lowest": "#0e0e0e",
              "on-primary-fixed-variant": "#852400",
              "on-tertiary-fixed-variant": "#004785"
            },
            fontFamily: {
              "headline": ["Space Grotesk"],
              "body": ["Inter"],
              "label": ["Space Grotesk"]
            },
            borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-comercio-tienda-stitch-02c.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
