const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-tertiary": "#222f51",
              "on-surface-variant": "#d0c5b5",
              "error": "#ffb4ab",
              "on-secondary-fixed-variant": "#454747",
              "on-tertiary-fixed-variant": "#394669",
              "on-surface": "#e5e2e1",
              "tertiary-fixed-dim": "#b8c5f0",
              "secondary-fixed-dim": "#c6c6c6",
              "tertiary-container": "#9facd5",
              "on-error": "#690005",
              "primary-fixed-dim": "#e3c285",
              "tertiary-fixed": "#dae2ff",
              "surface-container": "#201f1f",
              "background": "#131313",
              "inverse-primary": "#735b28",
              "surface-container-highest": "#353534",
              "error-container": "#93000a",
              "outline-variant": "#4d463a",
              "surface-variant": "#353534",
              "surface-container-low": "#1c1b1b",
              "inverse-surface": "#e5e2e1",
              "on-primary-container": "#533d0c",
              "on-secondary-fixed": "#1a1c1c",
              "surface-bright": "#3a3939",
              "secondary": "#c6c6c6",
              "surface": "#131313",
              "inverse-on-surface": "#313030",
              "on-error-container": "#ffdad6",
              "on-secondary-container": "#b5b5b5",
              "on-primary-fixed": "#261900",
              "primary-container": "#c8a96e",
              "surface-tint": "#e3c285",
              "primary": "#e5c487",
              "surface-dim": "#131313",
              "on-secondary": "#2f3131",
              "outline": "#998f81",
              "on-primary": "#402d00",
              "on-primary-fixed-variant": "#594312",
              "secondary-container": "#454747",
              "on-tertiary-fixed": "#0b1a3b",
              "surface-container-high": "#2a2a2a",
              "primary-fixed": "#ffdea3",
              "surface-container-lowest": "#0e0e0e",
              "on-tertiary-container": "#334063",
              "tertiary": "#bac7f2",
              "secondary-fixed": "#e2e2e2",
              "on-background": "#e5e2e1"
            },
            fontFamily: {
              "headline": ["Playfair Display", "serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-clinica-spa-stitch-02.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
