const baseConfig = {
            darkMode: "class",
            theme: {
                extend: {
                    colors: {
                        "surface": "#131313",
                        "on-primary-container": "#521300",
                        "on-tertiary-fixed": "#001c3a",
                        "surface-bright": "#3a3939",
                        "secondary-container": "#45464e",
                        "inverse-primary": "#ae3200",
                        "secondary": "#c6c6cf",
                        "on-secondary": "#2f3037",
                        "on-tertiary-container": "#002a53",
                        "on-surface": "#e5e2e1",
                        "secondary-fixed": "#e2e1eb",
                        "outline-variant": "#5c4037",
                        "error": "#ffb4ab",
                        "surface-container-highest": "#353534",
                        "surface-container-lowest": "#0e0e0e",
                        "error-container": "#93000a",
                        "primary-fixed-dim": "#ffb59e",
                        "primary-fixed": "#ffdbd0",
                        "on-secondary-container": "#b4b4bd",
                        "tertiary-container": "#2492ff",
                        "on-surface-variant": "#e6beb2",
                        "surface-container-low": "#1c1b1b",
                        "on-error-container": "#ffdad6",
                        "surface-container-high": "#2a2a2a",
                        "on-primary-fixed-variant": "#852400",
                        "surface-container": "#201f1f",
                        "on-primary-fixed": "#3a0b00",
                        "on-tertiary": "#00315e",
                        "on-secondary-fixed-variant": "#45464e",
                        "inverse-on-surface": "#313030",
                        "secondary-fixed-dim": "#c6c6cf",
                        "tertiary-fixed-dim": "#a5c8ff",
                        "on-error": "#690005",
                        "on-tertiary-fixed-variant": "#004785",
                        "on-secondary-fixed": "#1a1b22",
                        "on-primary": "#5e1700",
                        "surface-dim": "#131313",
                        "surface-variant": "#353534",
                        "tertiary-fixed": "#d4e3ff",
                        "primary-container": "#ff571a",
                        "background": "#131313",
                        "inverse-surface": "#e5e2e1",
                        "tertiary": "#a5c8ff",
                        "primary": "#ffb59e",
                        "outline": "#ad897e",
                        "on-background": "#e5e2e1",
                        "surface-tint": "#ffb59e"
                    },
                    fontFamily: {
                        "headline": ["Space Grotesk"],
                        "body": ["Inter"],
                        "label": ["Space Grotesk"]
                    },
                    borderRadius: {"DEFAULT": "0rem", "lg": "0rem", "xl": "0rem", "full": "9999px"},
                },
            },
        };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-comercio-tienda-stitch-02b.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
