const baseConfig = {
          darkMode: "class",
          theme: {
            extend: {
              colors: {
                "on-background": "#1d1b16",
                "secondary": "#705953",
                "on-tertiary-container": "#372c20",
                "primary": "#44664a",
                "surface-variant": "#e7e2d9",
                "on-primary-fixed": "#00210b",
                "on-secondary-fixed": "#281813",
                "on-error-container": "#93000a",
                "on-secondary-container": "#765f58",
                "surface": "#fff9ef",
                "inverse-on-surface": "#f6f0e7",
                "surface-container": "#f3ede4",
                "inverse-surface": "#32302a",
                "surface-tint": "#44664a",
                "tertiary-fixed": "#f3dfce",
                "outline": "#727971",
                "tertiary-container": "#a39283",
                "primary-fixed-dim": "#aad0ad",
                "tertiary-fixed-dim": "#d6c3b3",
                "on-tertiary": "#ffffff",
                "secondary-fixed": "#fbdcd3",
                "error-container": "#ffdad6",
                "on-surface": "#1d1b16",
                "surface-container-lowest": "#ffffff",
                "inverse-primary": "#aad0ad",
                "on-secondary-fixed-variant": "#57423c",
                "tertiary": "#6a5c4e",
                "primary-fixed": "#c6ecc8",
                "secondary-container": "#fbdcd3",
                "on-error": "#ffffff",
                "outline-variant": "#c2c8bf",
                "surface-container-highest": "#e7e2d9",
                "on-secondary": "#ffffff",
                "primary-container": "#7a9e7e",
                "on-primary-fixed-variant": "#2d4e33",
                "surface-bright": "#fff9ef",
                "error": "#ba1a1a",
                "background": "#fff9ef",
                "secondary-fixed-dim": "#dec0b8",
                "surface-container-high": "#ede7de",
                "surface-container-low": "#f9f3ea",
                "on-primary": "#ffffff",
                "on-surface-variant": "#424842",
                "surface-dim": "#dfd9d1",
                "on-tertiary-fixed": "#231a0f",
                "on-tertiary-fixed-variant": "#514538",
                "on-primary-container": "#13341c"
              },
              fontFamily: {
                "headline": ["Cormorant Garamond", "serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "serif": ["Noto Serif", "serif"]
              },
              borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
            },
          },
        };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-clinica-spa-stitch.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
