const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface-container-highest": "#353534",
              "outline-variant": "#4d4635",
              "tertiary": "#dfcbac",
              "primary-fixed": "#ffdea5",
              "on-error": "#690005",
              "secondary-container": "#474747",
              "secondary-fixed-dim": "#c8c6c5",
              "on-secondary": "#303030",
              "primary-container": "#d4ad65",
              "on-primary-fixed-variant": "#5d4201",
              "surface-bright": "#393939",
              "background": "#131313",
              "error": "#ffb4ab",
              "surface-container-high": "#2a2a2a",
              "on-tertiary-fixed-variant": "#52452d",
              "on-primary-container": "#5b4000",
              "surface-container-low": "#1c1b1b",
              "on-primary": "#412d00",
              "on-surface-variant": "#d0c5af",
              "on-tertiary-fixed": "#241a06",
              "surface-dim": "#131313",
              "primary": "#f1c97d",
              "surface-variant": "#353534",
              "on-primary-fixed": "#261900",
              "on-secondary-fixed": "#1b1c1c",
              "on-background": "#e5e2e1",
              "secondary": "#c8c6c5",
              "on-tertiary-container": "#50432b",
              "surface-tint": "#e9c176",
              "inverse-surface": "#e5e2e1",
              "outline": "#99907c",
              "tertiary-fixed": "#f4e0bf",
              "tertiary-container": "#c3b092",
              "on-error-container": "#ffdad6",
              "on-secondary-container": "#b6b5b4",
              "surface": "#131313",
              "inverse-on-surface": "#313030",
              "surface-container": "#201f1f",
              "on-tertiary": "#3a2f19",
              "tertiary-fixed-dim": "#d7c4a5",
              "secondary-fixed": "#e4e2e1",
              "primary-fixed-dim": "#e9c176",
              "inverse-primary": "#775a19",
              "on-secondary-fixed-variant": "#474747",
              "surface-container-lowest": "#0e0e0e",
              "on-surface": "#e5e2e1",
              "error-container": "#93000a"
            },
            fontFamily: {
              "headline": ["Noto Serif"],
              "body": ["Manrope"],
              "label": ["Manrope"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/maqueta-academia-formacion-stitch-03.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
