const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-primary-container": "#461f00",
              "tertiary-fixed-dim": "#d2c4b2",
              "surface": "#131313",
              "inverse-on-surface": "#313030",
              "on-primary-fixed": "#311400",
              "secondary": "#c8c6c5",
              "on-tertiary-fixed-variant": "#4f4538",
              "surface-container": "#20201f",
              "on-error-container": "#ffdad6",
              "surface-container-high": "#2a2a2a",
              "error-container": "#93000a",
              "on-tertiary-container": "#30291c",
              "primary-container": "#d37b38",
              "inverse-surface": "#e5e2e1",
              "on-primary-fixed-variant": "#723600",
              "surface-dim": "#131313",
              "on-surface": "#e5e2e1",
              "outline-variant": "#554336",
              "primary": "#ffb786",
              "inverse-primary": "#944a05",
              "surface-container-low": "#1c1b1b",
              "outline": "#a38c7c",
              "secondary-fixed-dim": "#c8c6c5",
              "surface-tint": "#ffb786",
              "on-tertiary-fixed": "#221a0f",
              "on-secondary-fixed-variant": "#474747",
              "on-secondary-container": "#b6b5b4",
              "on-primary": "#502400",
              "surface-container-lowest": "#0e0e0e",
              "on-tertiary": "#372f22",
              "primary-fixed-dim": "#ffb786",
              "primary-fixed": "#ffdcc6",
              "secondary-fixed": "#e4e2e1",
              "surface-bright": "#393939",
              "on-background": "#e5e2e1",
              "secondary-container": "#474747",
              "tertiary-container": "#9b8f7e",
              "tertiary-fixed": "#efe0cd",
              "surface-container-highest": "#353535",
              "error": "#ffb4ab",
              "on-surface-variant": "#dbc2b0",
              "tertiary": "#d2c4b2",
              "on-secondary-fixed": "#1b1c1c",
              "background": "#131313",
              "on-error": "#690005",
              "surface-variant": "#353535",
              "on-secondary": "#303030"
            },
            fontFamily: {
              "headline": ["Noto Serif", "serif"],
              "body": ["Manrope", "sans-serif"],
              "label": ["Manrope", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-restauracion-stitch.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
