const baseConfig = {
          darkMode: "class",
          theme: {
            extend: {
              colors: {
                "on-secondary-container": "#2f6c64",
                "secondary-fixed": "#b1eee4",
                "surface-container-highest": "#e1e3e4",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#f3f4f5",
                "on-primary": "#ffffff",
                "error": "#ba1a1a",
                "primary": "#000e27",
                "on-primary-container": "#728bbc",
                "on-primary-fixed": "#001b3e",
                "surface-container": "#edeeef",
                "tertiary": "#160d00",
                "on-surface": "#191c1d",
                "surface-container-high": "#e7e8e9",
                "background": "#f8f9fa",
                "surface-dim": "#d9dadb",
                "surface": "#f8f9fa",
                "secondary-fixed-dim": "#95d2c8",
                "on-secondary-fixed-variant": "#095049",
                "outline-variant": "#c4c6d0",
                "tertiary-fixed-dim": "#e9c176",
                "on-surface-variant": "#44474f",
                "primary-container": "#00234e",
                "surface-bright": "#f8f9fa",
                "primary-fixed-dim": "#adc7fb",
                "error-container": "#ffdad6",
                "surface-container-lowest": "#ffffff",
                "on-error-container": "#93000a",
                "tertiary-fixed": "#ffdea5",
                "surface-tint": "#445f8c",
                "on-error": "#ffffff",
                "primary-fixed": "#d7e3ff",
                "on-tertiary-container": "#a88642",
                "tertiary-container": "#312100",
                "secondary-container": "#aeece1",
                "on-background": "#191c1d",
                "inverse-on-surface": "#f0f1f2",
                "on-tertiary-fixed": "#261900",
                "surface-variant": "#e1e3e4",
                "on-tertiary-fixed-variant": "#5d4201",
                "inverse-primary": "#adc7fb",
                "secondary": "#2b6860",
                "inverse-surface": "#2e3132",
                "on-primary-fixed-variant": "#2c4773",
                "on-secondary-fixed": "#00201c",
                "on-secondary": "#ffffff",
                "outline": "#747780"
              },
              fontFamily: {
                "headline": ["Noto Serif"],
                "body": ["Inter"],
                "label": ["Work Sans"]
              },
              borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
            },
          },
        };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-academia-formacion-stitch-01.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
