const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-tertiary": "#ffffff",
              "primary": "#061b0e",
              "on-tertiary-fixed": "#231a11",
              "tertiary-fixed-dim": "#d5c3b6",
              "error": "#ba1a1a",
              "tertiary-container": "#342920",
              "surface-container-low": "#f4f4ef",
              "surface-tint": "#4d6453",
              "surface-container": "#eeeee9",
              "error-container": "#ffdad6",
              "on-secondary-fixed-variant": "#5d4201",
              "surface-variant": "#e3e3de",
              "on-tertiary-container": "#a08f83",
              "primary-fixed": "#d0e9d4",
              "inverse-primary": "#b4cdb8",
              "tertiary": "#1e150d",
              "on-tertiary-fixed-variant": "#51443a",
              "secondary": "#775a19",
              "secondary-fixed-dim": "#e9c176",
              "on-primary-fixed": "#0b2013",
              "inverse-surface": "#2f312e",
              "surface-container-lowest": "#ffffff",
              "secondary-container": "#fed488",
              "surface-dim": "#dadad5",
              "on-primary-fixed-variant": "#364c3c",
              "outline-variant": "#c3c8c1",
              "on-secondary-container": "#785a1a",
              "surface-container-highest": "#e3e3de",
              "on-secondary-fixed": "#261900",
              "outline": "#737973",
              "on-error": "#ffffff",
              "surface": "#fafaf5",
              "on-primary": "#ffffff",
              "primary-fixed-dim": "#b4cdb8",
              "on-surface": "#1a1c19",
              "on-error-container": "#93000a",
              "on-primary-container": "#819986",
              "on-surface-variant": "#434843",
              "on-background": "#1a1c19",
              "inverse-on-surface": "#f1f1ec",
              "surface-container-high": "#e8e8e3",
              "secondary-fixed": "#ffdea5",
              "primary-container": "#1b3022",
              "tertiary-fixed": "#f2dfd1",
              "background": "#fafaf5",
              "on-secondary": "#ffffff",
              "surface-bright": "#fafaf5"
            },
            fontFamily: {
              "headline": ["Noto Serif"],
              "body": ["Manrope"],
              "label": ["Manrope"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./maqueta-comercio-tienda-stitch.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
