const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "primary-dim": "#1cd0ad",
              "on-primary-fixed": "#00483b",
              "tertiary": "#e8e5ff",
              "tertiary-fixed-dim": "#cbc9e9",
              "on-background": "#dbe6ff",
              "inverse-primary": "#006c58",
              "on-secondary-fixed": "#383f50",
              "primary-container": "#005142",
              "outline": "#4776bc",
              "error-container": "#7f2927",
              "primary-fixed-dim": "#4decc8",
              "tertiary-dim": "#cbc9e9",
              "surface-bright": "#002b5b",
              "surface-dim": "#010e24",
              "surface-tint": "#38debb",
              "inverse-surface": "#f9f9ff",
              "primary": "#38debb",
              "on-error": "#490106",
              "on-tertiary-fixed": "#383751",
              "on-primary-fixed-variant": "#006855",
              "error": "#ee7d77",
              "surface": "#010e24",
              "on-surface": "#dbe6ff",
              "secondary-container": "#343b4c",
              "primary-fixed": "#5ffbd6",
              "background": "#010e24",
              "on-secondary-container": "#b8bfd4",
              "error-dim": "#bb5551",
              "on-surface-variant": "#7facf6",
              "secondary": "#979eb2",
              "surface-container-high": "#001f44",
              "outline-variant": "#08478b",
              "surface-container-highest": "#002550",
              "on-tertiary-container": "#4b4a65",
              "surface-container-low": "#00132e",
              "surface-variant": "#002550",
              "secondary-fixed-dim": "#cdd4ea",
              "tertiary-fixed": "#d9d7f8",
              "tertiary-container": "#d9d7f8",
              "surface-container": "#001939",
              "surface-container-lowest": "#000000",
              "secondary-dim": "#979eb2",
              "secondary-fixed": "#dce2f8",
              "on-primary-container": "#47e8c4",
              "on-tertiary-fixed-variant": "#54546f",
              "on-secondary-fixed-variant": "#545b6d",
              "on-tertiary": "#53526e",
              "on-primary": "#00493b",
              "on-secondary": "#192030",
              "on-error-container": "#ff9993",
              "inverse-on-surface": "#48556e"
            },
            fontFamily: {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch-device-frames.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
