const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-error-container": "#93000a",
              "on-surface": "#1a1c1c",
              "inverse-on-surface": "#f1f1f1",
              "secondary-container": "#c1eca1",
              "on-tertiary-fixed": "#291800",
              "on-secondary-fixed-variant": "#2c4f15",
              "on-primary-fixed-variant": "#2d486d",
              "primary": "#022448",
              "on-error": "#ffffff",
              "on-primary": "#ffffff",
              "surface": "#f9f9f9",
              "error": "#ba1a1a",
              "on-secondary": "#ffffff",
              "on-tertiary": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "surface-container": "#eeeeee",
              "on-tertiary-fixed-variant": "#60410c",
              "on-primary-container": "#8aa4cf",
              "inverse-surface": "#2f3131",
              "secondary-fixed": "#c4efa3",
              "surface-variant": "#e2e2e2",
              "tertiary-fixed": "#ffddb2",
              "secondary-fixed-dim": "#a8d38a",
              "primary-fixed-dim": "#adc8f5",
              "tertiary-container": "#503300",
              "error-container": "#ffdad6",
              "surface-dim": "#dadada",
              "surface-tint": "#455f87",
              "surface-bright": "#f9f9f9",
              "surface-container-low": "#f3f3f3",
              "surface-container-highest": "#e2e2e2",
              "on-tertiary-container": "#c69b5f",
              "outline": "#74777f",
              "on-surface-variant": "#43474e",
              "outline-variant": "#c4c6cf",
              "primary-container": "#1e3a5f",
              "on-secondary-fixed": "#0a2100",
              "secondary": "#43682b",
              "surface-container-high": "#e8e8e8",
              "background": "#f9f9f9",
              "tertiary": "#341f00",
              "primary-fixed": "#d5e3ff",
              "inverse-primary": "#adc8f5",
              "on-secondary-container": "#476c2f",
              "tertiary-fixed-dim": "#edbf7f",
              "on-background": "#1a1c1c",
              "on-primary-fixed": "#001c3b"
            },
            fontFamily: {
              "headline": ["Noto Serif", "serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./index.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
