const baseConfig = {
          darkMode: "class",
          theme: {
            extend: {
              colors: {
                "primary": "#5bf06c",
                "surface": "#10141a",
                "surface-variant": "#31353c",
                "on-tertiary-container": "#454951",
                "inverse-surface": "#dfe2eb",
                "on-secondary-fixed": "#001c38",
                "on-primary-container": "#005517",
                "primary-fixed": "#6fff7b",
                "error": "#ffb4ab",
                "on-tertiary-fixed-variant": "#42474f",
                "primary-fixed-dim": "#4be260",
                "surface-container": "#1c2026",
                "secondary": "#a2c9ff",
                "secondary-container": "#0071c7",
                "outline-variant": "#3d4a3b",
                "secondary-fixed-dim": "#a2c9ff",
                "tertiary-container": "#b4b9c2",
                "surface-bright": "#353940",
                "tertiary-fixed-dim": "#c2c7d0",
                "surface-container-lowest": "#0a0e14",
                "on-background": "#dfe2eb",
                "on-tertiary": "#2c3138",
                "error-container": "#93000a",
                "surface-container-low": "#181c22",
                "surface-dim": "#10141a",
                "on-secondary": "#00315c",
                "on-surface": "#dfe2eb",
                "background": "#10141a",
                "inverse-primary": "#006e20",
                "on-primary-fixed": "#002205",
                "tertiary-fixed": "#dee2ec",
                "on-tertiary-fixed": "#171c23",
                "on-error-container": "#ffdad6",
                "surface-container-high": "#262a31",
                "inverse-on-surface": "#2d3137",
                "on-surface-variant": "#bccbb6",
                "on-error": "#690005",
                "on-secondary-container": "#f0f4ff",
                "tertiary": "#d0d4de",
                "outline": "#869582",
                "surface-container-highest": "#31353c",
                "secondary-fixed": "#d3e4ff",
                "on-primary-fixed-variant": "#005316",
                "primary-container": "#39d353",
                "on-primary": "#00390c",
                "surface-tint": "#4be260",
                "on-secondary-fixed-variant": "#004882"
              },
              fontFamily: {
                "headline": ["JetBrains Mono"],
                "body": ["Inter"],
                "label": ["JetBrains Mono"]
              },
              borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "0px"},
            },
          },
        };

module.exports = {
  ...baseConfig,
  content: ["./stitch/freelance-03/index.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
