const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "inverse-primary": "#006e20",
              "primary-fixed-dim": "#4be260",
              "on-tertiary-fixed": "#171c23",
              "on-background": "#dfe2eb",
              "error-container": "#93000a",
              "secondary": "#a2c9ff",
              "on-surface-variant": "#bccbb6",
              "on-tertiary": "#2c3138",
              "on-surface": "#dfe2eb",
              "surface-bright": "#353940",
              "outline": "#869582",
              "tertiary-container": "#b4b9c2",
              "on-primary": "#00390c",
              "surface-variant": "#31353c",
              "secondary-container": "#0071c7",
              "secondary-fixed": "#d3e4ff",
              "on-secondary": "#00315c",
              "tertiary-fixed": "#dee2ec",
              "on-primary-fixed": "#002205",
              "inverse-surface": "#dfe2eb",
              "tertiary": "#d0d4de",
              "surface-container-highest": "#31353c",
              "on-secondary-fixed": "#001c38",
              "secondary-fixed-dim": "#a2c9ff",
              "on-error-container": "#ffdad6",
              "surface-dim": "#10141a",
              "error": "#ffb4ab",
              "surface": "#10141a",
              "on-secondary-fixed-variant": "#004882",
              "on-secondary-container": "#f0f4ff",
              "surface-container-lowest": "#0a0e14",
              "on-tertiary-fixed-variant": "#42474f",
              "on-primary-fixed-variant": "#005316",
              "surface-container-high": "#262a31",
              "surface-container": "#1c2026",
              "outline-variant": "#3d4a3b",
              "primary": "#5bf06c",
              "on-tertiary-container": "#454951",
              "tertiary-fixed-dim": "#c2c7d0",
              "surface-tint": "#4be260",
              "primary-container": "#39d353",
              "primary-fixed": "#6fff7b",
              "on-error": "#690005",
              "background": "#10141a",
              "on-primary-container": "#005517",
              "inverse-on-surface": "#2d3137",
              "surface-container-low": "#181c22"
            },
            fontFamily: {
              "headline": ["Space Grotesk"],
              "body": ["Inter"],
              "label": ["Inter"],
              "mono": ["JetBrains Mono"]
            },
            borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./portfolio.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
