const baseConfig = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "tertiary-container": "#909191",
              "surface-bright": "#3a3939",
              "outline-variant": "#524152",
              "secondary-fixed-dim": "#abd600",
              "secondary-container": "#c3f400",
              "surface-container": "#201f1f",
              "secondary": "#ffffff",
              "on-tertiary-fixed-variant": "#454747",
              "error": "#ffb4ab",
              "primary-fixed-dim": "#faabff",
              "on-secondary-fixed": "#161e00",
              "on-primary-container": "#4c0059",
              "primary-fixed": "#ffd6fe",
              "surface-variant": "#353534",
              "surface": "#131313",
              "primary": "#faabff",
              "on-tertiary-container": "#282a2a",
              "inverse-surface": "#e5e2e1",
              "on-primary-fixed-variant": "#7b008f",
              "surface-tint": "#faabff",
              "primary-container": "#e446ff",
              "on-secondary-fixed-variant": "#3c4d00",
              "on-primary": "#570066",
              "tertiary": "#c6c6c7",
              "surface-container-highest": "#353534",
              "secondary-fixed": "#c3f400",
              "outline": "#9f8a9e",
              "on-error": "#690005",
              "on-secondary-container": "#556d00",
              "surface-container-high": "#2a2a2a",
              "inverse-on-surface": "#313030",
              "on-surface-variant": "#d7c0d4",
              "background": "#131313",
              "tertiary-fixed": "#e2e2e2",
              "on-tertiary-fixed": "#1a1c1c",
              "on-primary-fixed": "#35003f",
              "inverse-primary": "#a200bb",
              "on-error-container": "#ffdad6",
              "surface-dim": "#131313",
              "on-surface": "#e5e2e1",
              "on-secondary": "#283500",
              "on-background": "#e5e2e1",
              "on-tertiary": "#2f3131",
              "surface-container-low": "#1c1b1b",
              "error-container": "#93000a",
              "tertiary-fixed-dim": "#c6c6c7",
              "surface-container-lowest": "#0e0e0e"
            },
            fontFamily: {
              "headline": ["Space Grotesk"],
              "body": ["Inter"],
              "label": ["Space Grotesk"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      };

module.exports = {
  ...baseConfig,
  content: ["./stitch/freelance-01/index.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
