const baseConfig = {
          darkMode: "class",
          theme: {
            extend: {
              colors: {
                "on-secondary-fixed-variant": "#3c4d00",
                "on-tertiary": "#2f3131",
                "on-error": "#690005",
                "tertiary-fixed-dim": "#c6c6c7",
                "on-tertiary-fixed-variant": "#454747",
                "on-secondary-fixed": "#161e00",
                "inverse-on-surface": "#313030",
                "secondary-fixed-dim": "#abd600",
                "on-primary": "#570066",
                "surface-dim": "#131313",
                "surface-variant": "#353534",
                "tertiary-fixed": "#e2e2e2",
                "background": "#131313",
                "primary-container": "#e446ff",
                "tertiary": "#c6c6c7",
                "inverse-surface": "#e5e2e1",
                "surface-tint": "#faabff",
                "outline": "#9f8a9e",
                "primary": "#faabff",
                "on-background": "#e5e2e1",
                "on-tertiary-fixed": "#1a1c1c",
                "surface": "#131313",
                "on-primary-container": "#4c0059",
                "surface-bright": "#3a3939",
                "secondary-container": "#c3f400",
                "inverse-primary": "#a200bb",
                "on-surface": "#e5e2e1",
                "on-tertiary-container": "#282a2a",
                "on-secondary": "#283500",
                "secondary": "#ffffff",
                "outline-variant": "#524152",
                "secondary-fixed": "#c3f400",
                "surface-container-lowest": "#0e0e0e",
                "error-container": "#93000a",
                "primary-fixed-dim": "#faabff",
                "error": "#ffb4ab",
                "surface-container-highest": "#353534",
                "primary-fixed": "#ffd6fe",
                "on-secondary-container": "#556d00",
                "surface-container-low": "#1c1b1b",
                "on-error-container": "#ffdad6",
                "on-surface-variant": "#d7c0d4",
                "tertiary-container": "#909191",
                "surface-container": "#201f1f",
                "on-primary-fixed": "#35003f",
                "surface-container-high": "#2a2a2a",
                "on-primary-fixed-variant": "#7b008f"
              },
              fontFamily: {
                "headline": ["Space Grotesk"],
                "body": ["Inter"],
                "label": ["Space Grotesk"]
              },
              borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
            },
          },
        };

module.exports = {
  ...baseConfig,
  content: ["./stitch/freelance-01/portfolio.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    ...((baseConfig.plugins) || []),
  ],
};
